language: java
jdk:
  - oraclejdk7
addons:
  apt:
    packages:
      - python-setuptools
      - gradle
before_install:
  - gradle -v
  - sudo easy_install pygments==1.5
script: "gradle --full-stacktrace test build"
notifications:
    email:
        recipients:
            - luna.bd@gmail.com
            - fernando.stefanini@caelum.com.br
            - marcosalles@gmail.com
        on_success: change
        on_failure: always
